trigger:
  - master

jobs:
  - job:
    condition: succeeded()
    strategy:
      maxParallel: 1
      matrix:
        'GP-Backend - MacOS':
          imjs_backend: 1
          os: macOS-latest
        'Local-Backend - MacOS':
          imjs_backend: 0
          os: macOS-latest

    pool:
      vmImage: $(os)
    steps:
      - checkout: self
        clean: all
      - task: NodeTool@0
        displayName: 'Install Node 12.x'
        inputs:
          versionSpec: 12.x
          checkLatest: true
      - script: node ./common/scripts/install-run-rush.js install
        displayName: Rush install
      - script: node ./common/scripts/install-run-rush.js build -v --to simple-viewer-app
        displayName: Rush build - Simple Viewer
      - script: node ./common/scripts/install-run-rush.js build -v --to imodel-query-agent
        displayName: Rush build - iModel Query Agent
      - script: node ./common/scripts/install-run-rush.js build -v --to imodel-changeset-test-utility
        displayName: Rush build - iModel Changeset Utility
      - script: node ./common/scripts/install-run-rush.js test:integration -v
        displayName: Rush Integration Test
